CREATE TABLE reportes(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razon_reporte VARCHAR(500) NOT NULL,
    fecha_reporte TIMESTAMP,
    estado_reporte VARCHAR(20) NOT NULL DEFAULT 'EN_REVISION',
    perfil_reportante INTEGER NOT NULL,
    perfil_reportado INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);