CREATE TABLE matches (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    perfil_a_id INTEGER NOT NULL,
    perfil_b_id INTEGER NOT NULL,
    status ENUM('ACTIVE', 'UNMATCHED') NOT NULL,
    matched_at TIMESTAMP NOT NULL
);
