server:
  port: 8084

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: usuarios-service
              uri: lb://usuarios
              predicates:
                - Path=/api/v2/usuarios/**, /usuarios/api-docs/**
            - id: auth-service
              uri: lb://usuarios
              predicates:
                - Path=/api/v2/auth/**
            - id: perfiles-service
              uri: lb://usuarios
              predicates:
                - Path=/api/v2/perfiles/**
            - id: comunas-service
              uri: lb://usuarios
              predicates:
                - Path=/api/v2/comunas/**
            - id: regiones-service
              uri: lb://usuarios
              predicates:
                - Path=/api/v2/regiones/**
            - id: preferencias-service
              uri: lb://usuarios
              predicates:
                - Path=/api/v2/preferencias/**
            - id: interaccion-service
              uri: lb://interaccion
              predicates:
                - Path=/api/v2/swipes/**, /api/v2/matches/**, /api/v2/mensajes/**, /api/v2/notificaciones/**, /interaccion/api-docs/**
            - id: reporte-service
              uri: lb://reporte
              predicates:
                - Path=/api/v2/reportes/**, /reporte/api-docs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: Microservicio Usuarios
        url: /usuarios/api-docs
      - name: Microservicio Interaccion
        url: /interaccion/api-docs
      - name: Microservicio Reporte
        url: /reporte/api-docs
  api-docs:
    enabled: true
