-- Modelo base de datos LoveU
-- Script basado en las entidades JPA del proyecto.
-- Pensado para PostgreSQL.

DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS reportes CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS swipes CASCADE;
DROP TABLE IF EXISTS foto_perfil CASCADE;
DROP TABLE IF EXISTS preferencias CASCADE;
DROP TABLE IF EXISTS perfiles CASCADE;
DROP TABLE IF EXISTS auth CASCADE;
DROP TABLE IF EXISTS comunas CASCADE;
DROP TABLE IF EXISTS regiones CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primer_nombre VARCHAR(50) NOT NULL,
    primer_apellido VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    telefono VARCHAR(20),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE auth (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    usuario_id INTEGER,

    CONSTRAINT fk_auth_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
);

CREATE TABLE regiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_region VARCHAR(50) NOT NULL,
    abreviacion VARCHAR(4) NOT NULL
);

CREATE TABLE comunas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comuna VARCHAR(50) NOT NULL,
    region_id INTEGER NOT NULL,

    CONSTRAINT fk_comunas_region
        FOREIGN KEY (region_id)
        REFERENCES regiones(id)
);

CREATE TABLE perfiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    biografia VARCHAR(500) NOT NULL,
    ocupacion VARCHAR(80) NOT NULL,
    altura_cm INTEGER,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    usuario_id INTEGER NOT NULL,
    comuna_id INTEGER NOT NULL,

    CONSTRAINT fk_perfiles_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id),

    CONSTRAINT fk_perfiles_comuna
        FOREIGN KEY (comuna_id)
        REFERENCES comunas(id),

    CONSTRAINT uk_perfiles_usuario
        UNIQUE (usuario_id),

    CONSTRAINT chk_perfiles_altura
        CHECK (altura_cm IS NULL OR altura_cm BETWEEN 100 AND 250)
);

CREATE TABLE preferencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id INTEGER NOT NULL,
    genero_deseado VARCHAR(20) NOT NULL,
    edad_minima INTEGER NOT NULL,
    edad_maxima INTEGER NOT NULL,
    distancia_maxima_km INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_preferencias_perfil
        FOREIGN KEY (perfil_id)
        REFERENCES perfiles(id),

    CONSTRAINT uk_preferencias_perfil
        UNIQUE (perfil_id),

    CONSTRAINT chk_preferencias_edad
        CHECK (edad_minima >= 18 AND edad_maxima BETWEEN 18 AND 99 AND edad_minima <= edad_maxima),

    CONSTRAINT chk_preferencias_distancia
        CHECK (distancia_maxima_km BETWEEN 1 AND 200)
);

CREATE TABLE foto_perfil (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id INTEGER NOT NULL,
    url_foto VARCHAR(255) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL,
    fecha_subida TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_foto_perfil_perfil
        FOREIGN KEY (perfil_id)
        REFERENCES perfiles(id),

    CONSTRAINT chk_foto_perfil_orden
        CHECK (orden BETWEEN 1 AND 6)
);

CREATE TABLE swipes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_origen_id INTEGER NOT NULL,
    perfil_destino_id INTEGER NOT NULL,
    decision VARCHAR(20) NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_swipes_origen
        FOREIGN KEY (perfil_origen_id)
        REFERENCES perfiles(id),

    CONSTRAINT fk_swipes_destino
        FOREIGN KEY (perfil_destino_id)
        REFERENCES perfiles(id),

    CONSTRAINT chk_swipes_decision
        CHECK (decision IN ('LIKE', 'DISLIKE', 'SKIP')),

    CONSTRAINT chk_swipes_perfiles_distintos
        CHECK (perfil_origen_id <> perfil_destino_id),

    CONSTRAINT uk_swipes_origen_destino
        UNIQUE (perfil_origen_id, perfil_destino_id)
);

CREATE TABLE matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_a_id INTEGER NOT NULL,
    perfil_b_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    matched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_matches_perfil_a
        FOREIGN KEY (perfil_a_id)
        REFERENCES perfiles(id),

    CONSTRAINT fk_matches_perfil_b
        FOREIGN KEY (perfil_b_id)
        REFERENCES perfiles(id),

    CONSTRAINT uk_matches_perfiles
        UNIQUE (perfil_a_id, perfil_b_id),

    CONSTRAINT chk_matches_status
        CHECK (status IN ('ACTIVE', 'UNMATCHED')),

    CONSTRAINT chk_matches_perfiles_distintos
        CHECK (perfil_a_id <> perfil_b_id)
);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL,
    perfil_emisor_id INTEGER NOT NULL,
    perfil_receptor_id INTEGER NOT NULL,
    contenido VARCHAR(1000) NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_messages_match
        FOREIGN KEY (match_id)
        REFERENCES matches(id),

    CONSTRAINT fk_messages_emisor
        FOREIGN KEY (perfil_emisor_id)
        REFERENCES perfiles(id),

    CONSTRAINT fk_messages_receptor
        FOREIGN KEY (perfil_receptor_id)
        REFERENCES perfiles(id),

    CONSTRAINT chk_messages_perfiles_distintos
        CHECK (perfil_emisor_id <> perfil_receptor_id)
);

CREATE TABLE reportes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_reportante_id INTEGER NOT NULL,
    perfil_reportado_id INTEGER NOT NULL,
    razon_reporte VARCHAR(500) NOT NULL,
    estado_reporte VARCHAR(20) NOT NULL DEFAULT 'EN_REVISION',
    fecha_reporte TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_reportes_reportante
        FOREIGN KEY (perfil_reportante_id)
        REFERENCES perfiles(id),

    CONSTRAINT fk_reportes_reportado
        FOREIGN KEY (perfil_reportado_id)
        REFERENCES perfiles(id),

    CONSTRAINT chk_reportes_estado
        CHECK (estado_reporte IN ('EN_REVISION', 'RESUELTO', 'RECHAZADO')),

    CONSTRAINT chk_reportes_perfiles_distintos
        CHECK (perfil_reportante_id <> perfil_reportado_id)
);

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_destinatario_id INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_perfil
        FOREIGN KEY (perfil_destinatario_id)
        REFERENCES perfiles(id),

    CONSTRAINT chk_notifications_type
        CHECK (type IN ('MATCH', 'MESSAGE', 'LIKE', 'REPORT'))
);

CREATE INDEX idx_comunas_region_id ON comunas(region_id);
CREATE INDEX idx_perfiles_comuna_id ON perfiles(comuna_id);
CREATE INDEX idx_swipes_origen_id ON swipes(perfil_origen_id);
CREATE INDEX idx_swipes_destino_id ON swipes(perfil_destino_id);
CREATE INDEX idx_matches_perfil_a_id ON matches(perfil_a_id);
CREATE INDEX idx_matches_perfil_b_id ON matches(perfil_b_id);
CREATE INDEX idx_messages_match_id ON messages(match_id);
CREATE INDEX idx_reportes_reportado_id ON reportes(perfil_reportado_id);
CREATE INDEX idx_notifications_destinatario_id ON notifications(perfil_destinatario_id);
