CREATE TABLE perfil(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_visible VARCHAR(30) NOT NULL,
    biografia VARCHAR(500) NOT NULL,
    ocupacion VARCHAR(30),
    altura_cm INTEGER,
    usuario_id INTEGER NOT NULL,
    comuna_id INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);
