CREATE TABLE comunas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comuna VARCHAR(50) NOT NULL,
    regionid INTEGER NOT NULL,
    CONSTRAINT fk_comuna_region FOREIGN KEY (regionid) REFERENCES regiones(id)
);
