CREATE TABLE foto_perfil (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id INTEGER NOT NULL,
    url_foto VARCHAR(255) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_subida TIMESTAMP,

    CONSTRAINT chk_orden CHECK (orden >= 1 AND orden <= 6),
    CONSTRAINT fk_foto_perfil FOREIGN KEY (perfil_id) REFERENCES perfil(id)
);
