CREATE TABLE preferencia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id INTEGER NOT NULL UNIQUE,
    edad_min INTEGER NOT NULL,
    edad_max INTEGER NOT NULL,
    distancia_max_km INTEGER NOT NULL,
    altura_min_cm INTEGER,
    altura_max_cm INTEGER,
    genero_preferido VARCHAR(20) NOT NULL DEFAULT 'Todos',
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_edad CHECK (edad_min >= 18 AND edad_max >= edad_min),
    CONSTRAINT chk_distancia CHECK (distancia_max_km >= 1),
    CONSTRAINT chk_altura CHECK (altura_min_cm IS NULL OR altura_max_cm IS NULL OR altura_max_cm >= altura_min_cm),
    CONSTRAINT fk_preferencia_perfil FOREIGN KEY (perfil_id) REFERENCES perfil(id)
);
